window.config = {
    URL_BONITO: "https://localhost/bonito/run.cgi/",

    NO_SKE: true,
    NO_CA: true,
    READ_ONLY: false,
    READ_ONLY_MSG: "",
    //NOTIFICATION: "",

    links: {
        "wl_download_limits": "https://www.sketchengine.eu/guide/access-to-unlimited-wordlists/",
        "priceList": "https://www.sketchengine.eu/price-list/",
        "quickStartGuide": "https://www.sketchengine.eu/quick-start-guide/",
        "userGuide": "https://www.sketchengine.eu/user-guide/",
        "sketchEngineIntro": "https://www.youtube.com/embed/f4eszLB47Qk",
        "cqlIntro": "https://www.youtube.com/embed/nOMr_D6ISRM",
        "concordanceBasicVideo": "https://www.youtube.com/embed/FzI6tbO5EvQ",
        "youtubeChannel": "https://www.youtube.com/channel/UCo2fn2_SNxCikCSAFCBcWBw",
        "privacyPolicy": "https://www.sketchengine.eu/gdpr-privacy-consent/",
        "serviceRequest": "https://www.lexicalcomputing.com/request-language-data-or-services/",
        "globalAdministration": "",
        "parallelCorporaFileFormats" : "https://www.sketchengine.eu/guide/setting-up-parallel-corpora/",
        "supportMail": "support@sketchengine.eu",
        "bootCamp": "https://www.sketchengine.eu/bootcamp/",
        "cqlManual": "https://www.sketchengine.eu/documentation/corpus-querying/",
        "regexManual": "https://www.sketchengine.eu/guide/regular-expressions/",
        "updateBrowser": "https://browsehappy.com/",
        "compareCorpora": "https://www.sketchengine.eu/guide/compare-corpora/",
        "multiLingualCorpora": "https://www.sketchengine.eu/guide/setting-up-parallel-corpora/",
        "h_lemma": " https://www.sketchengine.eu/my_keywords/lemma/",
        "h_collocate": " https://www.sketchengine.eu/my_keywords/collocate/",
        "h_subcorpus": "https://www.sketchengine.eu/my_keywords/subcorpus/",
        "h_frequency": "https://www.sketchengine.eu/my_keywords/freqmill/",
        "h_wordForm": "https://www.sketchengine.eu/my_keywords/word-form/",
        "h_subcorpus": "https://www.sketchengine.eu/my_keywords/subcorpus/",
        "h_regex": "https://www.sketchengine.eu/guide/regular-expressions/",
        "h_token": "https://www.sketchengine.eu/my_keywords/token/",
        "h_KWIC": "https://www.sketchengine.eu/my_keywords/kwic/",
        "h_attribute": "https://www.sketchengine.eu/my_keywords/positional-attribute/",
        "h_lc": "https://www.sketchengine.eu/my_keywords/lc/",
        "h_tag": "https://www.sketchengine.eu/my_keywords/tag/",
        "h_lempos": "https://www.sketchengine.eu/my_keywords/lempos/",
        "h_structure": "https://www.sketchengine.eu/my_keywords/structure/",
        "h_annotating": "https://www.sketchengine.eu/guide/annotating-corpus-text/",
        "h_relfreq": "https://www.sketchengine.eu/my_keywords/freqmill/",
        "cb_basics": "https://www.sketchengine.eu/documentation/cql-basics/",
        "cb_structures": "https://www.sketchengine.eu/documentation/cql-search-structures/",
        "cb_within_containing": "https://www.sketchengine.eu/documentation/cql-within-containing/",
        "cb_meet": "https://www.sketchengine.eu/documentation/cql-meet-union/",
        "cb_wordsketch": "https://www.sketchengine.eu/documentation/cql-word-sketches/",
        "cb_thesaurus": "https://www.sketchengine.eu/documentation/cql-thesaurus/",
        "cb_global_conditions": "https://www.sketchengine.eu/documentation/cql-global-conditions/"
    }
}
